### ISSUE TITLE
_fzf_complete_sf:11 permission denied

### ISSUE THREAD

**Issue by benjaminloerincz** [cristiand391/sf-plugin-fzf-cmp#6]
Hi Cristian,

first of all, thank you very much for this tool.

After installation, adjusting .zshrc, restarting / resourcing everything, the completion does work for example for `sf ,` as we can see here:

![image](https://github.com/cristiand391/sf-plugin-fzf-cmp/assets/18007134/0db9f42b-204a-4636-9151-6e9c758b7fd2)

But, unfortunately, it does not work for `sf org open -o ,` or `sf org open --target-org ,`. For a millisecond I can see this error:
> _fzf_complete_sf:11: permission denied: /Users/benjaminloerincz/.local/share/sf/client/2.47.6-6b39a27/bin/dev. cmd

How can I resolve this issue? Is there some error in my setup?

**Comment by cristiand391** [comment]
Hey @benjaminloerincz 👋🏼 

That looks like an issue with your installation (missing perms, `bin/dev.cmd` isn't really used - it's for windows only). Can you Can you try re-installing `sf` and run `sf fzf-cmp` again?
https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli.htm
